title: Welcome to ADummy's Blog
author: ADummt
email: guanshanqiu@zju.edu.cn
description: > # this means to ignore newlines until "baseurl:"
  
  Cybersecurity.

# social links
#twitter_username: your-twitter-handle # DO NOT include the @ character, or else the build will fail!
github_username:  ADummmy # DO NOT include the @ character, or else the build will fail!

show_excerpts: true # set to false to remove excerpts on the homepage
